[
  {
    id: 1,
    name: 'кирпич',
    list_subname: 'кирпич, Кирпич',
    metal: false,
    density: 1.8,
    density_min: 1.7,
    density_max: 1.9,
    density_sko: 0.043,
    density_distrib: 'normal',
    coef_density_change: 0.4989,
    coef_density_change_sko: 0.0256,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: 1.6807,
    alfa_coef_floor_wall_min: 1.4768,
    alfa_coef_floor_wall_max: 1.8846,
    beta_coef_floor_wall: 5.0957,
    beta_coef_floor_wall_min: 5.0,
    beta_coef_floor_wall_max: 5.1914,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 2,
    name: 'штукатурка',
    list_subname: 'Штукатурка, штукатурка, Краска, краска',
    metal: false,
    density: 1.8,
    density_min: 1.7,
    density_max: 1.9,
    density_sko: 0.043,
    density_distrib: 'normal ',
    coef_density_change: 0.7784,
    coef_density_change_sko: 0.0291,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: 1.6807,
    alfa_coef_floor_wall_min: 1.4768,
    alfa_coef_floor_wall_max: 1.8846,
    beta_coef_floor_wall: 5.0957,
    beta_coef_floor_wall_min: 5.0,
    beta_coef_floor_wall_max: 5.1914,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 3,
    name: 'керамическая плитка',
    list_subname: 'Керамическая плитка, керамическая плитка',
    metal: false,
    density: 1.9,
    density_min: 1.8,
    density_max: 2.0,
    density_sko: 0.043,
    density_distrib: 'normal ',
    coef_density_change: 0.6579,
    coef_density_change_sko: 0.0186,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 4,
    name: 'пластикат',
    list_subname: 'Пластикат, пластикат, пластикат (пол)',
    metal: false,
    density: 1.5,
    density_min: 1.5,
    density_max: 1.5,
    density_sko: 0.0,
    density_distrib: 'const',
    coef_density_change: 0.7002,
    coef_density_change_sko: 0.0142,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 5,
    name: 'бетонная плитка',
    list_subname: 'Бетонная плитка, бетонная плитка',
    metal: false,
    density: 2.35,
    density_min: 2.3,
    density_max: 2.4,
    density_sko: 0.021,
    density_distrib: 'normal ',
    coef_density_change: 0.4682,
    coef_density_change_sko: 0.019,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 6,
    name: 'оборудование (сталь)',
    list_subname: 'Оборудование, сталь, металл',
    metal: true,
    density: 8.0,
    density_min: 7.7,
    density_max: 8.3,
    density_sko: 0.129,
    density_distrib: 'normal ',
    coef_density_change: 0.1,
    coef_density_change_sko: 0.01,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 7,
    name: 'чистый металл',
    list_subname: null,
    metal: false,
    density: null,
    density_min: null,
    density_max: null,
    density_sko: null,
    density_distrib: null,
    coef_density_change: null,
    coef_density_change_sko: null,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 8,
    name: 'строительный мусор',
    list_subname: null,
    metal: false,
    density: null,
    density_min: null,
    density_max: null,
    density_sko: null,
    density_distrib: null,
    coef_density_change: null,
    coef_density_change_sko: null,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 9,
    name: 'грунт',
    list_subname: null,
    metal: false,
    density: null,
    density_min: null,
    density_max: null,
    density_sko: null,
    density_distrib: null,
    coef_density_change: null,
    coef_density_change_sko: null,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 11,
    name: 'чугунная плитка',
    list_subname: 'Чугунная плитка, чугунная плитка, плитка чугунная',
    metal: true,
    density: 7.0,
    density_min: 6.8,
    density_max: 7.2,
    density_sko: 0.086,
    density_distrib: 'normal ',
    coef_density_change: 0.3561,
    coef_density_change_sko: 0.0307,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 12,
    name: 'металлическая плитка',
    list_subname: 'Металлическая плитка, металлическая плитка',
    metal: true,
    density: 7.75,
    density_min: 7.6,
    density_max: 7.9,
    density_sko: 0.064,
    density_distrib: 'normal ',
    coef_density_change: 0.2261,
    coef_density_change_sko: 0.0144,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 16,
    name: 'бетон (пол)',
    list_subname: 'Бетон, бетон, бетон (пол)',
    metal: false,
    density: 2.45,
    density_min: 2.4,
    density_max: 2.5,
    density_sko: 0.021,
    density_distrib: 'normal ',
    coef_density_change: 0.264,
    coef_density_change_sko: 0.0267,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 17,
    name: 'дерево',
    list_subname: 'Дерево, дерево',
    metal: false,
    density: 0.6,
    density_min: 0.5,
    density_max: 0.7,
    density_sko: 0.043,
    density_distrib: 'normal ',
    coef_density_change: 0.6733,
    coef_density_change_sko: 0.0834,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 18,
    name: 'Железобетон',
    list_subname: null,
    metal: false,
    density: 3.3,
    density_min: 2.5,
    density_max: 4.1,
    density_sko: 0.34,
    density_distrib: 'normal ',
    coef_density_change: 0.3683,
    coef_density_change_sko: 0.044,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 19,
    name: 'Прочее',
    list_subname: null,
    metal: false,
    density: 1.2,
    density_min: 1.2,
    density_max: 1.2,
    density_sko: 0.0,
    density_distrib: 'const',
    coef_density_change: 1.0,
    coef_density_change_sko: 0.0,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 20,
    name: 'Камень',
    list_subname: 'Камень, камень',
    metal: false,
    density: 2.5,
    density_min: 2.0,
    density_max: 3.0,
    density_sko: 0.21,
    density_distrib: 'normal ',
    coef_density_change: 0.7048,
    coef_density_change_sko: 0.0771,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 21,
    name: 'Металлическое перекрытие',
    list_subname: null,
    metal: true,
    density: 7.75,
    density_min: 7.6,
    density_max: 7.9,
    density_sko: 0.06,
    density_distrib: 'normal ',
    coef_density_change: 0.1808,
    coef_density_change_sko: 0.0113,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 22,
    name: 'Стальные перегородки',
    list_subname: 'Стальные перегородки, стальные перегородки',
    metal: true,
    density: 1.0,
    density_min: 0.8,
    density_max: 1.2,
    density_sko: 0.09,
    density_distrib: 'normal ',
    coef_density_change: 0.5037,
    coef_density_change_sko: 0.0619,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: 2.6821,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 23,
    name: 'деревянное перекрытие',
    list_subname: 'Деревянное перекрытие, деревянное перекрытие',
    metal: false,
    density: 0.6,
    density_min: 0.5,
    density_max: 0.7,
    density_sko: 0.043,
    density_distrib: 'normal ',
    coef_density_change: 0.6733,
    coef_density_change_sko: 0.0834,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 24,
    name: 'деревянный паркет',
    list_subname: 'Деревянный паркет, деревянный паркет',
    metal: false,
    density: 0.6,
    density_min: 0.5,
    density_max: 0.7,
    density_sko: 0.043,
    density_distrib: 'normal ',
    coef_density_change: 0.6733,
    coef_density_change_sko: 0.0834,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 45,
    name: 'теплоизоляция',
    list_subname: 'Теплоизоляция, теплоизоляция',
    metal: false,
    density: 1.2,
    density_min: 1.2,
    density_max: 1.2,
    density_sko: 0.0,
    density_distrib: 'const',
    coef_density_change: 1.0,
    coef_density_change_sko: 0.0,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 46,
    name: 'стяжка',
    list_subname: 'Стяжка, стяжка',
    metal: false,
    density: 2.35,
    density_min: 2.3,
    density_max: 2.4,
    density_sko: 0.021,
    density_distrib: 'normal ',
    coef_density_change: 0.4682,
    coef_density_change_sko: 0.019,
    coef_density_change_distrib: null,
    alfa_kiro: 58.2565539386,
    alfa_kiro_min: 73.7954051948,
    alfa_kiro_max: 42.7177026823,
    beta_kiro: 12.6666601986,
    beta_kiro_min: 16.728973005,
    beta_kiro_max: 8.6043473922,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
  {
    id: 47,
    name: 'Цельное оборудование',
    list_subname: 'Оборудование, сталь, металл',
    metal: true,
    density: 8.0,
    density_min: 7.7,
    density_max: 8.3,
    density_sko: 0.129,
    density_distrib: 'normal ',
    coef_density_change: 0.1,
    coef_density_change_sko: 0.01,
    coef_density_change_distrib: null,
    alfa_kiro: 254.7416247086,
    alfa_kiro_min: 308.6576389151,
    alfa_kiro_max: 200.8256105022,
    beta_kiro: 4.90845,
    beta_kiro_min: 7.1348,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 48,
    name: 'ЖРО',
    list_subname: null,
    metal: false,
    density: null,
    density_min: null,
    density_max: null,
    density_sko: null,
    density_distrib: null,
    coef_density_change: null,
    coef_density_change_sko: null,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'жидкий',
    flammability_type: false,
  },
  {
    id: 49,
    name: 'Осадок',
    list_subname: null,
    metal: false,
    density: null,
    density_min: null,
    density_max: null,
    density_sko: null,
    density_distrib: null,
    coef_density_change: null,
    coef_density_change_sko: null,
    coef_density_change_distrib: null,
    alfa_kiro: null,
    alfa_kiro_min: null,
    alfa_kiro_max: null,
    beta_kiro: null,
    beta_kiro_min: null,
    beta_kiro_max: null,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: true,
  },
  {
    id: 50,
    name: 'Хвосты гидрометаллургического, химико-металлургического, разделительного и сублиматного производств,пульпы, образующиеся после нейтрализации',
    list_subname: null,
    metal: false,
    density: 2.5,
    density_min: 2.0,
    density_max: 3.0,
    density_sko: 0.21,
    density_distrib: 'normal ',
    coef_density_change: 0.7048,
    coef_density_change_sko: 0.0771,
    coef_density_change_distrib: null,
    alfa_kiro: 43.0657783699,
    alfa_kiro_min: 52.9007932399,
    alfa_kiro_max: 33.2307634998,
    beta_kiro: 3.5941768436,
    beta_kiro_min: 4.4520999854,
    beta_kiro_max: 2.7362537019,
    alfa_coef_floor_wall: null,
    alfa_coef_floor_wall_min: null,
    alfa_coef_floor_wall_max: null,
    beta_coef_floor_wall: null,
    beta_coef_floor_wall_min: null,
    beta_coef_floor_wall_max: null,
    dataset_id: 2,
    ag_type: 'твердый',
    flammability_type: false,
  },
]